const countries = [
  {
    value: '+93',
    label: 'Afghanistan',
    iso2: 'af',
    priority: 0,
  },
  {
    value: '+355',
    label: 'Albania',
    iso2: 'al',
    priority: 0,
  },
  {
    value: '+213',
    label: 'Algeria',
    iso2: 'dz',
    priority: 0,
  },
  {
    value: '+1684',
    label: 'American Samoa',
    iso2: 'as',
    priority: 0,
  },
  {
    value: '+376',
    label: 'Andorra',
    iso2: 'ad',
    priority: 0,
  },
  {
    value: '+244',
    label: 'Angola',
    iso2: 'ao',
    priority: 0,
  },
  {
    value: '+1264',
    label: 'Anguilla',
    iso2: 'ai',
    priority: 0,
  },
  {
    value: '+1268',
    label: 'Antigua and Barbuda',
    iso2: 'ag',
    priority: 0,
  },
  {
    value: '+54',
    label: 'Argentina',
    iso2: 'ar',
    priority: 0,
  },
  {
    value: '+374',
    label: 'Armenia',
    iso2: 'am',
    priority: 0,
  },
  {
    value: '+297',
    label: 'Aruba',
    iso2: 'aw',
    priority: 0,
  },
  {
    value: '+61',
    label: 'Australia',
    iso2: 'au',
    priority: 0,
  },
  {
    value: '+43',
    label: 'Austria',
    iso2: 'at',
    priority: 0,
  },
  {
    value: '+994',
    label: 'Azerbaijan',
    iso2: 'az',
    priority: 0,
  },
  {
    value: '+1242',
    label: 'Bahamas',
    iso2: 'bs',
    priority: 0,
  },
  {
    value: '+973',
    label: 'Bahrain',
    iso2: 'bh',
    priority: 0,
  },
  {
    value: '+880',
    label: 'Bangladesh',
    iso2: 'bd',
    priority: 0,
  },
  {
    value: '+1246',
    label: 'Barbados',
    iso2: 'bb',
    priority: 0,
  },
  {
    value: '+375',
    label: 'Belarus',
    iso2: 'by',
    priority: 0,
  },
  {
    value: '+32',
    label: 'Belgium',
    iso2: 'be',
    priority: 0,
  },
  {
    value: '+501',
    label: 'Belize',
    iso2: 'bz',
    priority: 0,
  },
  {
    value: '+229',
    label: 'Benin',
    iso2: 'bj',
    priority: 0,
  },
  {
    value: '+1441',
    label: 'Bermuda',
    iso2: 'bm',
    priority: 0,
  },
  {
    value: '+975',
    label: 'Bhutan',
    iso2: 'bt',
    priority: 0,
  },
  {
    value: '+591',
    label: 'Bolivia',
    iso2: 'bo',
    priority: 0,
  },
  {
    value: '+387',
    label: 'Bosnia and Herzegovina',
    iso2: 'ba',
    priority: 0,
  },
  {
    value: '+267',
    label: 'Botswana',
    iso2: 'bw',
    priority: 0,
  },
  {
    value: '+55',
    label: 'Brazil',
    iso2: 'br',
    priority: 0,
  },
  {
    value: '+246',
    label: 'British Indian Ocean Territory',
    iso2: 'io',
    priority: 0,
  },
  {
    value: '+1284',
    label: 'British Virgin Islands',
    iso2: 'vg',
    priority: 0,
  },
  {
    value: '+673',
    label: 'Brunei',
    iso2: 'bn',
    priority: 0,
  },
  {
    value: '+359',
    label: 'Bulgaria',
    iso2: 'bg',
    priority: 0,
  },
  {
    value: '+226',
    label: 'Burkina Faso',
    iso2: 'bf',
    priority: 0,
  },
  {
    value: '+257',
    label: 'Burundi',
    iso2: 'bi',
    priority: 0,
  },
  {
    value: '+855',
    label: 'Cambodia',
    iso2: 'kh',
    priority: 0,
  },
  {
    value: '+237',
    label: 'Cameroon',
    iso2: 'cm',
    priority: 0,
  },
  {
    value: '+1',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1204',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1236',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1249',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1250',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1289',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1306',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1343',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1365',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1387',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1403',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1416',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1418',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1431',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1437',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1438',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1450',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1506',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1514',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1519',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1548',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1579',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1581',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1587',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1604',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1613',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1639',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1647',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1672',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1705',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1709',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1742',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1778',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1780',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1782',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1807',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1819',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1825',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1867',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1873',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1902',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+1905',
    label: 'Canada',
    iso2: 'ca',
    priority: 1,
  },
  {
    value: '+238',
    label: 'Cape Verde',
    iso2: 'cv',
    priority: 0,
  },
  {
    value: '+599',
    label: 'Caribbean Netherlands',
    iso2: 'bq',
    priority: 1,
  },
  {
    value: '+1345',
    label: 'Cayman Islands',
    iso2: 'ky',
    priority: 0,
  },
  {
    value: '+236',
    label: 'Central African Republic',
    iso2: 'cf',
    priority: 0,
  },
  {
    value: '+235',
    label: 'Chad',
    iso2: 'td',
    priority: 0,
  },
  {
    value: '+56',
    label: 'Chile',
    iso2: 'cl',
    priority: 0,
  },
  {
    value: '+86',
    label: 'China',
    iso2: 'cn',
    priority: 0,
  },
  {
    value: '+57',
    label: 'Colombia',
    iso2: 'co',
    priority: 0,
  },
  {
    value: '+269',
    label: 'Comoros',
    iso2: 'km',
    priority: 0,
  },
  {
    value: '+243',
    label: 'Congo',
    iso2: 'cd',
    priority: 0,
  },
  {
    value: '+242',
    label: 'Congo',
    iso2: 'cg',
    priority: 0,
  },
  {
    value: '+682',
    label: 'Cook Islands',
    iso2: 'ck',
    priority: 0,
  },
  {
    value: '+506',
    label: 'Costa Rica',
    iso2: 'cr',
    priority: 0,
  },
  {
    value: '+225',
    label: 'Côte d’Ivoire',
    iso2: 'ci',
    priority: 0,
  },
  {
    value: '+385',
    label: 'Croatia',
    iso2: 'hr',
    priority: 0,
  },
  {
    value: '+53',
    label: 'Cuba',
    iso2: 'cu',
    priority: 0,
  },
  {
    value: '+599',
    label: 'Curaçao',
    iso2: 'cw',
    priority: 0,
  },
  {
    value: '+357',
    label: 'Cyprus',
    iso2: 'cy',
    priority: 0,
  },
  {
    value: '+420',
    label: 'Czech Republic',
    iso2: 'cz',
    priority: 0,
  },
  {
    value: '+45',
    label: 'Denmark',
    iso2: 'dk',
    priority: 0,
  },
  {
    value: '+253',
    label: 'Djibouti',
    iso2: 'dj',
    priority: 0,
  },
  {
    value: '+1767',
    label: 'Dominica',
    iso2: 'dm',
    priority: 0,
  },
  {
    value: '+1',
    label: 'Dominican Republic',
    iso2: 'do',
    priority: 2,
  },
  {
    value: '+1809',
    label: 'Dominican Republic',
    iso2: 'do',
    priority: 2,
  },
  {
    value: '+1829',
    label: 'Dominican Republic',
    iso2: 'do',
    priority: 2,
  },
  {
    value: '+1849',
    label: 'Dominican Republic',
    iso2: 'do',
    priority: 2,
  },
  {
    value: '+593',
    label: 'Ecuador',
    iso2: 'ec',
    priority: 0,
  },
  {
    value: '+20',
    label: 'Egypt',
    iso2: 'eg',
    priority: 0,
  },
  {
    value: '+503',
    label: 'El Salvador',
    iso2: 'sv',
    priority: 0,
  },
  {
    value: '+240',
    label: 'Equatorial Guinea',
    iso2: 'gq',
    priority: 0,
  },
  {
    value: '+291',
    label: 'Eritrea',
    iso2: 'er',
    priority: 0,
  },
  {
    value: '+372',
    label: 'Estonia',
    iso2: 'ee',
    priority: 0,
  },
  {
    value: '+251',
    label: 'Ethiopia',
    iso2: 'et',
    priority: 0,
  },
  {
    value: '+500',
    label: 'Falkland Islands',
    iso2: 'fk',
    priority: 0,
  },
  {
    value: '+298',
    label: 'Faroe Islands',
    iso2: 'fo',
    priority: 0,
  },
  {
    value: '+679',
    label: 'Fiji',
    iso2: 'fj',
    priority: 0,
  },
  {
    value: '+358',
    label: 'Finland',
    iso2: 'fi',
    priority: 0,
  },
  {
    value: '+33',
    label: 'France',
    iso2: 'fr',
    priority: 0,
  },
  {
    value: '+594',
    label: 'French Guiana',
    iso2: 'gf',
    priority: 0,
  },
  {
    value: '+689',
    label: 'French Polynesia',
    iso2: 'pf',
    priority: 0,
  },
  {
    value: '+241',
    label: 'Gabon',
    iso2: 'ga',
    priority: 0,
  },
  {
    value: '+220',
    label: 'Gambia',
    iso2: 'gm',
    priority: 0,
  },
  {
    value: '+995',
    label: 'Georgia',
    iso2: 'ge',
    priority: 0,
  },
  {
    value: '+49',
    label: 'Germany',
    iso2: 'de',
    priority: 0,
  },
  {
    value: '+233',
    label: 'Ghana',
    iso2: 'gh',
    priority: 0,
  },
  {
    value: '+350',
    label: 'Gibraltar',
    iso2: 'gi',
    priority: 0,
  },
  {
    value: '+30',
    label: 'Greece',
    iso2: 'gr',
    priority: 0,
  },
  {
    value: '+299',
    label: 'Greenland',
    iso2: 'gl',
    priority: 0,
  },
  {
    value: '+1473',
    label: 'Grenada',
    iso2: 'gd',
    priority: 0,
  },
  {
    value: '+590',
    label: 'Guadeloupe',
    iso2: 'gp',
    priority: 0,
  },
  {
    value: '+1671',
    label: 'Guam',
    iso2: 'gu',
    priority: 0,
  },
  {
    value: '+502',
    label: 'Guatemala',
    iso2: 'gt',
    priority: 0,
  },
  {
    value: '+224',
    label: 'Guinea',
    iso2: 'gn',
    priority: 0,
  },
  {
    value: '+245',
    label: 'Guinea-Bissau',
    iso2: 'gw',
    priority: 0,
  },
  {
    value: '+592',
    label: 'Guyana',
    iso2: 'gy',
    priority: 0,
  },
  {
    value: '+509',
    label: 'Haiti',
    iso2: 'ht',
    priority: 0,
  },
  {
    value: '+504',
    label: 'Honduras',
    iso2: 'hn',
    priority: 0,
  },
  {
    value: '+852',
    label: 'Hong Kong',
    iso2: 'hk',
    priority: 0,
  },
  {
    value: '+36',
    label: 'Hungary',
    iso2: 'hu',
    priority: 0,
  },
  {
    value: '+354',
    label: 'Iceland',
    iso2: 'is',
    priority: 0,
  },
  {
    value: '+91',
    label: 'India',
    iso2: 'in',
    priority: 0,
  },
  {
    value: '+62',
    label: 'Indonesia',
    iso2: 'id',
    priority: 0,
  },
  {
    value: '+98',
    label: 'Iran',
    iso2: 'ir',
    priority: 0,
  },
  {
    value: '+964',
    label: 'Iraq',
    iso2: 'iq',
    priority: 0,
  },
  {
    value: '+353',
    label: 'Ireland',
    iso2: 'ie',
    priority: 0,
  },
  {
    value: '+972',
    label: 'Israel',
    iso2: 'il',
    priority: 0,
  },
  {
    value: '+39',
    label: 'Italy',
    iso2: 'it',
    priority: 0,
  },
  {
    value: '+1876',
    label: 'Jamaica',
    iso2: 'jm',
    priority: 0,
  },
  {
    value: '+81',
    label: 'Japan',
    iso2: 'jp',
    priority: 0,
  },
  {
    value: '+962',
    label: 'Jordan',
    iso2: 'jo',
    priority: 0,
  },
  {
    value: '+7',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7313',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7327',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+77172',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7312',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+773622',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7321',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7324',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7336',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7318',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7315',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7325',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7311',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7326',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+7310',
    label: 'Kazakhstan',
    iso2: 'kz',
    priority: 1,
  },
  {
    value: '+254',
    label: 'Kenya',
    iso2: 'ke',
    priority: 0,
  },
  {
    value: '+686',
    label: 'Kiribati',
    iso2: 'ki',
    priority: 0,
  },
  {
    value: '+965',
    label: 'Kuwait',
    iso2: 'kw',
    priority: 0,
  },
  {
    value: '+996',
    label: 'Kyrgyzstan',
    iso2: 'kg',
    priority: 0,
  },
  {
    value: '+856',
    label: 'Laos',
    iso2: 'la',
    priority: 0,
  },
  {
    value: '+371',
    label: 'Latvia',
    iso2: 'lv',
    priority: 0,
  },
  {
    value: '+961',
    label: 'Lebanon',
    iso2: 'lb',
    priority: 0,
  },
  {
    value: '+266',
    label: 'Lesotho',
    iso2: 'ls',
    priority: 0,
  },
  {
    value: '+231',
    label: 'Liberia',
    iso2: 'lr',
    priority: 0,
  },
  {
    value: '+218',
    label: 'Libya',
    iso2: 'ly',
    priority: 0,
  },
  {
    value: '+423',
    label: 'Liechtenstein',
    iso2: 'li',
    priority: 0,
  },
  {
    value: '+370',
    label: 'Lithuania',
    iso2: 'lt',
    priority: 0,
  },
  {
    value: '+352',
    label: 'Luxembourg',
    iso2: 'lu',
    priority: 0,
  },
  {
    value: '+853',
    label: 'Macau',
    iso2: 'mo',
    priority: 0,
  },
  {
    value: '+389',
    label: 'Macedonia',
    iso2: 'mk',
    priority: 0,
  },
  {
    value: '+261',
    label: 'Madagascar',
    iso2: 'mg',
    priority: 0,
  },
  {
    value: '+265',
    label: 'Malawi',
    iso2: 'mw',
    priority: 0,
  },
  {
    value: '+60',
    label: 'Malaysia',
    iso2: 'my',
    priority: 0,
  },
  {
    value: '+960',
    label: 'Maldives',
    iso2: 'mv',
    priority: 0,
  },
  {
    value: '+223',
    label: 'Mali',
    iso2: 'ml',
    priority: 0,
  },
  {
    value: '+356',
    label: 'Malta',
    iso2: 'mt',
    priority: 0,
  },
  {
    value: '+692',
    label: 'Marshall Islands',
    iso2: 'mh',
    priority: 0,
  },
  {
    value: '+596',
    label: 'Martinique',
    iso2: 'mq',
    priority: 0,
  },
  {
    value: '+222',
    label: 'Mauritania',
    iso2: 'mr',
    priority: 0,
  },
  {
    value: '+230',
    label: 'Mauritius',
    iso2: 'mu',
    priority: 0,
  },
  {
    value: '+52',
    label: 'Mexico',
    iso2: 'mx',
    priority: 0,
  },
  {
    value: '+691',
    label: 'Micronesia',
    iso2: 'fm',
    priority: 0,
  },
  {
    value: '+373',
    label: 'Moldova',
    iso2: 'md',
    priority: 0,
  },
  {
    value: '+377',
    label: 'Monaco',
    iso2: 'mc',
    priority: 0,
  },
  {
    value: '+976',
    label: 'Mongolia',
    iso2: 'mn',
    priority: 0,
  },
  {
    value: '+382',
    label: 'Montenegro',
    iso2: 'me',
    priority: 0,
  },
  {
    value: '+1664',
    label: 'Montserrat',
    iso2: 'ms',
    priority: 0,
  },
  {
    value: '+212',
    label: 'Morocco',
    iso2: 'ma',
    priority: 0,
  },
  {
    value: '+258',
    label: 'Mozambique',
    iso2: 'mz',
    priority: 0,
  },
  {
    value: '+95',
    label: 'Myanmar',
    iso2: 'mm',
    priority: 0,
  },
  {
    value: '+264',
    label: 'Namibia',
    iso2: 'na',
    priority: 0,
  },
  {
    value: '+674',
    label: 'Nauru',
    iso2: 'nr',
    priority: 0,
  },
  {
    value: '+977',
    label: 'Nepal',
    iso2: 'np',
    priority: 0,
  },
  {
    value: '+31',
    label: 'Netherlands',
    iso2: 'nl',
    priority: 0,
  },
  {
    value: '+687',
    label: 'New Caledonia',
    iso2: 'nc',
    priority: 0,
  },
  {
    value: '+64',
    label: 'New Zealand',
    iso2: 'nz',
    priority: 0,
  },
  {
    value: '+505',
    label: 'Nicaragua',
    iso2: 'ni',
    priority: 0,
  },
  {
    value: '+227',
    label: 'Niger',
    iso2: 'ne',
    priority: 0,
  },
  {
    value: '+234',
    label: 'Nigeria',
    iso2: 'ng',
    priority: 0,
  },
  {
    value: '+683',
    label: 'Niue',
    iso2: 'nu',
    priority: 0,
  },
  {
    value: '+672',
    label: 'Norfolk Island',
    iso2: 'nf',
    priority: 0,
  },
  {
    value: '+850',
    label: 'North Korea',
    iso2: 'kp',
    priority: 0,
  },
  {
    value: '+1670',
    label: 'Northern Mariana Islands',
    iso2: 'mp',
    priority: 0,
  },
  {
    value: '+47',
    label: 'Norway',
    iso2: 'no',
    priority: 0,
  },
  {
    value: '+968',
    label: 'Oman',
    iso2: 'om',
    priority: 0,
  },
  {
    value: '+92',
    label: 'Pakistan',
    iso2: 'pk',
    priority: 0,
  },
  {
    value: '+680',
    label: 'Palau',
    iso2: 'pw',
    priority: 0,
  },
  {
    value: '+970',
    label: 'Palestine',
    iso2: 'ps',
    priority: 0,
  },
  {
    value: '+507',
    label: 'Panama',
    iso2: 'pa',
    priority: 0,
  },
  {
    value: '+675',
    label: 'Papua New Guinea',
    iso2: 'pg',
    priority: 0,
  },
  {
    value: '+595',
    label: 'Paraguay',
    iso2: 'py',
    priority: 0,
  },
  {
    value: '+51',
    label: 'Peru',
    iso2: 'pe',
    priority: 0,
  },
  {
    value: '+63',
    label: 'Philippines',
    iso2: 'ph',
    priority: 0,
  },
  {
    value: '+48',
    label: 'Poland',
    iso2: 'pl',
    priority: 0,
  },
  {
    value: '+351',
    label: 'Portugal',
    iso2: 'pt',
    priority: 0,
  },
  {
    value: '+1',
    label: 'Puerto Rico',
    iso2: 'pr',
    priority: 3,
  },
  {
    value: '+1787',
    label: 'Puerto Rico',
    iso2: 'pr',
    priority: 3,
  },
  {
    value: '+1939',
    label: 'Puerto Rico',
    iso2: 'pr',
    priority: 3,
  },
  {
    value: '+974',
    label: 'Qatar',
    iso2: 'qa',
    priority: 0,
  },
  {
    value: '+262',
    label: 'Réunion',
    iso2: 're',
    priority: 0,
  },
  {
    value: '+40',
    label: 'Romania',
    iso2: 'ro',
    priority: 0,
  },
  {
    value: '+7',
    label: 'Russia',
    iso2: 'ru',
    priority: 0,
  },
  {
    value: '+250',
    label: 'Rwanda',
    iso2: 'rw',
    priority: 0,
  },
  {
    value: '+590',
    label: 'Saint Barthélemy',
    iso2: 'bl',
    priority: 1,
  },
  {
    value: '+290',
    label: 'Saint Helena',
    iso2: 'sh',
    priority: 0,
  },
  {
    value: '+1869',
    label: 'Saint Kitts and Nevis',
    iso2: 'kn',
    priority: 0,
  },
  {
    value: '+1758',
    label: 'Saint Lucia',
    iso2: 'lc',
    priority: 0,
  },
  {
    value: '+590',
    label: 'Saint Martin',
    iso2: 'mf',
    priority: 2,
  },
  {
    value: '+508',
    label: 'Saint Pierre and Miquelon',
    iso2: 'pm',
    priority: 0,
  },
  {
    value: '+1784',
    label: 'Saint Vincent and the Grenadines',
    iso2: 'vc',
    priority: 0,
  },
  {
    value: '+685',
    label: 'Samoa',
    iso2: 'ws',
    priority: 0,
  },
  {
    value: '+378',
    label: 'San Marino',
    iso2: 'sm',
    priority: 0,
  },
  {
    value: '+239',
    label: 'São Tomé and Príncipe',
    iso2: 'st',
    priority: 0,
  },
  {
    value: '+966',
    label: 'Saudi Arabia',
    iso2: 'sa',
    priority: 0,
  },
  {
    value: '+221',
    label: 'Senegal',
    iso2: 'sn',
    priority: 0,
  },
  {
    value: '+381',
    label: 'Serbia',
    iso2: 'rs',
    priority: 0,
  },
  {
    value: '+248',
    label: 'Seychelles',
    iso2: 'sc',
    priority: 0,
  },
  {
    value: '+232',
    label: 'Sierra Leone',
    iso2: 'sl',
    priority: 0,
  },
  {
    value: '+65',
    label: 'Singapore',
    iso2: 'sg',
    priority: 0,
  },
  {
    value: '+1721',
    label: 'Sint Maarten',
    iso2: 'sx',
    priority: 0,
  },
  {
    value: '+421',
    label: 'Slovakia',
    iso2: 'sk',
    priority: 0,
  },
  {
    value: '+386',
    label: 'Slovenia',
    iso2: 'si',
    priority: 0,
  },
  {
    value: '+677',
    label: 'Solomon Islands',
    iso2: 'sb',
    priority: 0,
  },
  {
    value: '+252',
    label: 'Somalia',
    iso2: 'so',
    priority: 0,
  },
  {
    value: '+27',
    label: 'South Africa',
    iso2: 'za',
    priority: 0,
  },
  {
    value: '+82',
    label: 'South Korea',
    iso2: 'kr',
    priority: 0,
  },
  {
    value: '+211',
    label: 'South Sudan',
    iso2: 'ss',
    priority: 0,
  },
  {
    value: '+34',
    label: 'Spain',
    iso2: 'es',
    priority: 0,
  },
  {
    value: '+94',
    label: 'Sri Lanka',
    iso2: 'lk',
    priority: 0,
  },
  {
    value: '+249',
    label: 'Sudan',
    iso2: 'sd',
    priority: 0,
  },
  {
    value: '+597',
    label: 'Suriname',
    iso2: 'sr',
    priority: 0,
  },
  {
    value: '+268',
    label: 'Swaziland',
    iso2: 'sz',
    priority: 0,
  },
  {
    value: '+46',
    label: 'Sweden',
    iso2: 'se',
    priority: 0,
  },
  {
    value: '+41',
    label: 'Switzerland',
    iso2: 'ch',
    priority: 0,
  },
  {
    value: '+963',
    label: 'Syria',
    iso2: 'sy',
    priority: 0,
  },
  {
    value: '+886',
    label: 'Taiwan',
    iso2: 'tw',
    priority: 0,
  },
  {
    value: '+992',
    label: 'Tajikistan',
    iso2: 'tj',
    priority: 0,
  },
  {
    value: '+255',
    label: 'Tanzania',
    iso2: 'tz',
    priority: 0,
  },
  {
    value: '+66',
    label: 'Thailand',
    iso2: 'th',
    priority: 0,
  },
  {
    value: '+670',
    label: 'Timor-Leste',
    iso2: 'tl',
    priority: 0,
  },
  {
    value: '+228',
    label: 'Togo',
    iso2: 'tg',
    priority: 0,
  },
  {
    value: '+690',
    label: 'Tokelau',
    iso2: 'tk',
    priority: 0,
  },
  {
    value: '+676',
    label: 'Tonga',
    iso2: 'to',
    priority: 0,
  },
  {
    value: '+1868',
    label: 'Trinidad and Tobago',
    iso2: 'tt',
    priority: 0,
  },
  {
    value: '+216',
    label: 'Tunisia',
    iso2: 'tn',
    priority: 0,
  },
  {
    value: '+90',
    label: 'Turkey',
    iso2: 'tr',
    priority: 0,
  },
  {
    value: '+993',
    label: 'Turkmenistan',
    iso2: 'tm',
    priority: 0,
  },
  {
    value: '+1649',
    label: 'Turks and Caicos Islands',
    iso2: 'tc',
    priority: 0,
  },
  {
    value: '+688',
    label: 'Tuvalu',
    iso2: 'tv',
    priority: 0,
  },
  {
    value: '+1340',
    label: 'U.S. Virgin Islands',
    iso2: 'vi',
    priority: 0,
  },
  {
    value: '+256',
    label: 'Uganda',
    iso2: 'ug',
    priority: 0,
  },
  {
    value: '+380',
    label: 'Ukraine',
    iso2: 'ua',
    priority: 0,
  },
  {
    value: '+971',
    label: 'United Arab Emirates',
    iso2: 'ae',
    priority: 0,
  },
  {
    value: '+44',
    label: 'United Kingdom',
    iso2: 'gb',
    priority: 0,
  },
  {
    value: '+598',
    label: 'Uruguay',
    iso2: 'uy',
    priority: 0,
  },
  {
    value: '+998',
    label: 'Uzbekistan',
    iso2: 'uz',
    priority: 0,
  },
  {
    value: '+678',
    label: 'Vanuatu',
    iso2: 'vu',
    priority: 0,
  },
  {
    value: '+39',
    label: 'Vatican City',
    iso2: 'va',
    priority: 1,
  },
  {
    value: '+58',
    label: 'Venezuela',
    iso2: 've',
    priority: 0,
  },
  {
    value: '+84',
    label: 'Vietnam',
    iso2: 'vn',
    priority: 0,
  },
  {
    value: '+681',
    label: 'Wallis and Futuna',
    iso2: 'wf',
    priority: 0,
  },
  {
    value: '+967',
    label: 'Yemen',
    iso2: 'ye',
    priority: 0,
  },
  {
    value: '+260',
    label: 'Zambia',
    iso2: 'zm',
    priority: 0,
  },
  {
    value: '+263',
    label: 'Zimbabwe',
    iso2: 'zw',
    priority: 0,
  },
];

export default countries;
